# Generated by Django 3.2.3 on 2022-01-04 23:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shops',
            options={},
        ),
        migrations.RemoveField(
            model_name='shops',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shops',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='shops',
            name='store_addresses',
        ),
        migrations.RemoveField(
            model_name='shops',
            name='user',
        ),
        migrations.AddField(
            model_name='shops',
            name='store_addresse',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Адрес магазин'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('shop', models.ManyToManyField(blank=True, null=True, related_name='shop_marketplace', to='app_shops.Shops', verbose_name='Магазин')),
                ('user', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Польователь')),
            ],
            options={
                'verbose_name': 'marketplace',
                'verbose_name_plural': 'marketplace',
            },
        ),
    ]
