# Generated by Django 3.2.3 on 2022-01-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0002_auto_20220105_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='app_shops.Products', verbose_name='Товар'),
        ),
    ]
