# Generated by Django 3.2.3 on 2022-01-05 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0003_shops_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shops',
            name='products',
        ),
        migrations.CreateModel(
            name='ShopsProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shops.products')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shops.shops')),
            ],
        ),
        migrations.AddField(
            model_name='shops',
            name='product',
            field=models.ManyToManyField(through='app_shops.ShopsProducts', to='app_shops.Products'),
        ),
    ]
