# Generated by Django 3.2.3 on 2022-01-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0004_auto_20220106_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsproducts',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество товаров'),
        ),
    ]
