# Generated by Django 3.2.3 on 2022-01-07 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0006_remove_products_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='price_with_store',
        ),
    ]
