# Generated by Django 3.2.3 on 2022-01-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0008_history_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='basket',
            field=models.ManyToManyField(blank=True, null=True, related_name='basket', to='app_shops.ShopsProducts', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='history',
            name='purchase_history',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_history', to='app_shops.ShopsProducts', verbose_name='Продукт'),
        ),
    ]
