# Generated by Django 3.2.3 on 2022-01-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0010_auto_20220117_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='date_of_purchase',
            field=models.DateField(blank=True, null=True, verbose_name='Дата совершения покупки'),
        ),
    ]
