# Generated by Django 3.2.3 on 2022-01-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0011_history_date_of_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='contents_of_the_basket',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_basket', to='app_shops.ShopsProducts', verbose_name='Продукты в корзине'),
        ),
    ]
