# Generated by Django 3.2.3 on 2022-01-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shops', '0013_alter_marketplace_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='number_of_sales',
            field=models.IntegerField(default=0, verbose_name='Количество продаж'),
        ),
    ]
