# Generated by Django 3.2.3 on 2022-01-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('active_user', 'active user'), ('inactive user', 'inactive user')], default='inactive user', max_length=30, null=True),
        ),
    ]
